### ISSUE TITLE
is there a way to allow only Linux line endings?

### ISSUE THREAD

**Issue by modernNeo** [grantmcconnaughey/Flake8Rules#16]

**Comment by modernNeo** [comment]
@grantmcconnaughey does that mean there is no way to enforce this?

**Comment by grantmcconnaughey** [comment]
Apologies, I don't know why I closed that without comment. 😅 

This site is just for documenting Flake8 Rules, not Flake8 itself. If you have a question about Flake8 functionality itself I'd check out the Flake8 repo: https://gitlab.com/pycqa/flake8
