### ISSUE TITLE
Add support for https in flake8rules.com (Your connection is not private :)

### ISSUE THREAD

**Issue by lipis** [grantmcconnaughey/Flake8Rules#20]
http://www.flake8rules.com

**Comment by checktheroads** [comment]
@grantmcconnaughey - agreed on this one! My best recommendation would be to get a free [Netlify](https://www.netlify.com/) account and have Netlify auto build your site on new commits to master. [This guide](https://www.netlify.com/blog/2015/10/28/a-step-by-step-guide-jekyll-3.0-on-netlify/) from their blog looks pretty much all-inclusive of the very easy process. You could certainly do this with GitHub Pages as well, I just happens to find GH Pages to be obtuse and feature light.

I host several sites this way and pay nothing, if I can help in any way let me know!

**Comment by lipis** [comment]
Netlify is just awesome!!

**Comment by grantmcconnaughey** [comment]
Thanks for the heads up! I made some changes in NameCheap to configure this, and I _think_ its configured correctly now. Once confirmed I'll force HTTPS in the GitHub Pages settings.

@checktheroads I've heard really good things about Netlify. I'll definitely check that out for my next project.

**Comment by grantmcconnaughey** [comment]
The site is now redirecting traffic to HTTPS. Thanks @lipis and @checktheroads!
