### ISSUE TITLE
F722 is missing: do not use bare 'except'

### ISSUE THREAD

**Issue by jugmac00** [grantmcconnaughey/Flake8Rules#27]

**Comment by jugmac00** [comment]
I just saw this is a duplicate of #15 - which is already 10 months old.

I understand, you got more important stuff to do currently, but would you accept a PR?

**Comment by grantmcconnaughey** [comment]
@jugmac00 yes, absolutely! PRs are very much appreciated.

**Comment by grantmcconnaughey** [comment]
Duplicate of #15

**Comment by grantmcconnaughey** [comment]
Fixed!

**Comment by jugmac00** [comment]
Sorry for not contributing as I planned - it is like a curse. So many great open source projects out there, and only so and so much time!

Thank you very much! Your site was such a huge help when I started using flake8 on my inherited, huge Python project.
