### ISSUE TITLE
E117 is missing: overindented code blocks

### ISSUE THREAD

**Issue by jugmac00** [grantmcconnaughey/Flake8Rules#29]

**Comment by grantmcconnaughey** [comment]
Documented in `master`

**Comment by jugmac00** [comment]
Thanks! Do you manually build your website or do build it automatically?

**Comment by grantmcconnaughey** [comment]
I use GitHub pages, which builds it automatically. When I say "documented in `master`" what I mean is that I just documented it and pushed to `master`. So you're right; it was missing. Apologies for the confusion there!
