### ISSUE TITLE
Missing E999

### ISSUE THREAD

**Issue by tdhopper** [grantmcconnaughey/Flake8Rules#8]
[E999](https://github.com/PyCQA/flake8/blob/master/docs/source/user/error-codes.rst) indicates failure to generate AST (e.g. SyntaxError).

**Comment by lipis** [comment]
Why this one is not included?

**Comment by grantmcconnaughey** [comment]
Because it is awaiting your PR, @lipis! 😄

**Comment by grantmcconnaughey** [comment]
Fixed by #24
